name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-binaries:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          BIN_NAME=guangfu250923
          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o dist/${BIN_NAME}_${GOOS}_${GOARCH}${EXT} ./cmd/server/main.go
      - name: Copy OpenAPI spec
        run: |
          cp openapi.yaml dist/openapi.yaml

      - name: Generate checksums
        if: matrix.goos == 'windows'
        run: |
          # Only run once (arbitrary pick windows job) to generate global checksums file
          cd dist
          sha256sum * > SHA256SUMS.txt
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-aggregate

      - name: Re-assemble dist
        run: |
          mkdir -p dist
          find dist-aggregate -type f -exec cp {} dist/ \;
          ls -l dist
          # Ensure checksum file exists; if not generate one
          if [ ! -f dist/SHA256SUMS.txt ]; then
            (cd dist && sha256sum * > SHA256SUMS.txt)
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/guangfu250923_*
            dist/SHA256SUMS.txt
            dist/openapi.yaml
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
